version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-laravel-todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-todo_db
      MYSQL_USER: todo
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
